version: "3.8"
services:
    org-catalog-web:
        build:
            context: ./.docker/nginx
            dockerfile: web.dockerfile
        working_dir: /var/www
        container_name: org-catalog-web
        volumes:
            - ./:/var/www
        depends_on:
            - org-catalog-app
        ports:
            - 8080:80
        networks:
            - aggregator_network

    # PHP 8.2
    org-catalog-app:
        build:
            context: ./.docker/php
            dockerfile: app.dockerfile
        working_dir: /var/www/
        container_name: org-catalog-app
        volumes:
            - ./:/var/www
        depends_on:
            - org-catalog-db
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        networks:
            - aggregator_network

    # PostgreSQL 15
    org-catalog-db:
        image: postgis/postgis:15-3.4-alpine
        volumes:
            - dbdata:/var/lib/postgresql/data
        container_name: org-catalog-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - 5432:5432
        networks:
            - aggregator_network

volumes:
    dbdata:

networks:
    aggregator_network:
        driver: bridge
        name: org-catalog
